export enum FileErrorCause {
  INVALID_FILE_PATH = "INVALID_FILE_PATH",
  UNSUPPORTED_FILE_EXTENSION = "UNSUPPORTED_FILE_EXTENSION",
  INVALID_FILE_CONTENTS = "INVALID_FILE_CONTENTS",
  DUPLICATE_FILE_PATH = "DUPLICATE_FILE_PATH",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
}
