name: Set up Node.js

description: Install Node.js and npm dependencies

inputs:
  cache:
    description: Cache dependencies?
    required: false
    default: "true"

  node-version:
    description: Version of Node.js to install
    required: false

runs:
  using: composite

  steps:
    - name: Set up Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        package-manager-cache: false

    - name: Set up pnpm
      uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
      with:
        cache: ${{ inputs.cache }}
        run_install: true
