name: Set up Node.js

description: Install Node.js and npm dependencies

inputs:
  cache:
    description: Cache dependencies?
    required: false
    default: "true"

  runtime:
    description: Version of Node.js to install
    required: false

runs:
  using: composite

  steps:
    - name: Set up Node.js
      uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
      with:
        cache: ${{ inputs.cache }}
        runtime: ${{ inputs.runtime }}
