name: Set up Node.js

description: Install Node.js and npm dependencies

inputs:
  node-version:
    description: Version of Node.js to install

runs:
  using: composite

  steps:
    - name: Set up pnpm
      uses: pnpm/action-setup@v3

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}
        node-version-file: ${{ inputs.node-version == '' && '.node-version' || '' }}
        registry-url: https://registry.npmjs.com

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
