root: true

parser: "@typescript-eslint/parser"
parserOptions:
  project: true

plugins:
  - eslint-plugin-tsdoc
  - import

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:import/typescript

rules:
  "@typescript-eslint/consistent-type-imports": warn
  "@typescript-eslint/explicit-function-return-type": warn
  "@typescript-eslint/explicit-member-accessibility": warn
  "@typescript-eslint/no-confusing-void-expression": warn
  "@typescript-eslint/prefer-enum-initializers": warn
  "@typescript-eslint/prefer-nullish-coalescing": warn
  "@typescript-eslint/promise-function-async": warn
  "@typescript-eslint/return-await":
    - warn
    - always
  curly: warn
  func-style:
    - warn
    - declaration
  import/consistent-type-specifier-style:
    - warn
    - prefer-top-level
  import/export: warn
  import/newline-after-import: warn
  import/no-duplicates: warn
  import/no-extraneous-dependencies:
    - warn
    - devDependencies:
        - packages/scripts/src/**/*.ts
        - packages/test/src/**/*.ts
      optionalDependencies: false
      peerDependencies: false
      includeTypes: true
  import/no-named-as-default: warn
  import/order:
    - warn
    - alphabetize:
        order: asc
        orderImportKind: asc
        caseInsensitive: true
      newlines-between: always
  no-console: warn
  sort-imports:
    - warn
    - ignoreDeclarationSort: true
  tsdoc/syntax: warn
