root: true

parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - packages/*/tsconfig.json

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended

rules:
  "@typescript-eslint/consistent-type-imports": warn
  "@typescript-eslint/explicit-function-return-type": warn
  "@typescript-eslint/explicit-member-accessibility": warn
  "@typescript-eslint/no-confusing-void-expression": warn
  "@typescript-eslint/prefer-enum-initializers": warn
  "@typescript-eslint/promise-function-async": warn
  "@typescript-eslint/return-await":
    - warn
    - always
  curly: warn
  func-style:
    - warn
    - declaration
  import/no-duplicates: warn
  import/no-extraneous-dependencies:
    - warn
    - devDependencies:
        - packages/test/**/*.ts
      optionalDependencies: false
      peerDependencies: false
      includeTypes: true
  import/order:
    - warn
    - alphabetize:
        order: asc
        orderImportKind: asc
        caseInsensitive: true
      newlines-between: always
  no-console: warn
  sort-imports:
    - warn
    - ignoreDeclarationSort: true

overrides:
  - files:
      - "**/*.ts"
    plugins:
      - eslint-plugin-tsdoc
    rules:
      tsdoc/syntax: warn
