root: true

parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - packages/*/tsconfig.json

plugins:
  - import

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
  - plugin:import/typescript

rules:
  "@typescript-eslint/consistent-type-imports": warn
  "@typescript-eslint/explicit-function-return-type": warn
  "@typescript-eslint/explicit-member-accessibility": warn
  "@typescript-eslint/no-confusing-void-expression": warn
  "@typescript-eslint/prefer-enum-initializers": warn
  "@typescript-eslint/prefer-nullish-coalescing": warn
  "@typescript-eslint/promise-function-async": warn
  "@typescript-eslint/return-await":
    - warn
    - always
  curly: warn
  func-style:
    - warn
    - declaration
  import/export: warn
  import/newline-after-import: warn
  import/no-duplicates: warn
  import/no-extraneous-dependencies:
    - warn
    - devDependencies:
        - packages/test/**/*.ts
      optionalDependencies: false
      peerDependencies: false
      includeTypes: true
  import/no-named-as-default: warn
  import/order:
    - warn
    - alphabetize:
        order: asc
        orderImportKind: asc
        caseInsensitive: true
      newlines-between: always
  import/consistent-type-specifier-style:
    - warn
    - prefer-top-level
  no-console: warn
  sort-imports:
    - warn
    - ignoreDeclarationSort: true

overrides:
  - files:
      - "**/*.ts"
    plugins:
      - eslint-plugin-tsdoc
    rules:
      tsdoc/syntax: warn

  - files:
      - packages/test/src/**/*.test.ts
      - packages/test/src/helpers.ts
    extends:
      - plugin:vitest/recommended
    rules:
      "@typescript-eslint/no-unsafe-assignment": off
      "@typescript-eslint/no-unsafe-member-access": off
      "@typescript-eslint/no-unsafe-argument": off
