root: true

parser: "@typescript-eslint/parser"
parserOptions:
  project:
    - packages/*/tsconfig.json

plugins:
  - eslint-plugin-tsdoc

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:@typescript-eslint/recommended-requiring-type-checking
  - plugin:@typescript-eslint/strict
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:jest/recommended

rules:
  "@typescript-eslint/consistent-type-imports": error
  "@typescript-eslint/explicit-function-return-type": error
  "@typescript-eslint/explicit-member-accessibility": error
  "@typescript-eslint/no-confusing-void-expression": error
  "@typescript-eslint/prefer-enum-initializers": error
  "@typescript-eslint/promise-function-async": error
  "@typescript-eslint/return-await":
    - error
    - always
  curly: error
  import/no-duplicates: error
  import/no-extraneous-dependencies:
    - error
    - devDependencies:
        - packages/test/**/*.ts
      optionalDependencies: false
      peerDependencies: false
      includeTypes: true
  import/order:
    - error
    - alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  no-console: error
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  tsdoc/syntax: error
