packages:
  - packages/*
  - private/*

allowBuilds:
  "@bufbuild/buf": false
  esbuild: false
  protobufjs: false

linkWorkspacePackages: true

minimumReleaseAge: 7200 # 5 days
minimumReleaseAgeExclude:
  - "@cerbos/*"
  - react
  - react-dom
  - scheduler

saveExact: true
