packages:
  - packages/*
  - private/*

ignoredBuiltDependencies:
  - "@bufbuild/buf"
  - esbuild
  - protobufjs

linkWorkspacePackages: true

minimumReleaseAge: 7200 # 5 days
minimumReleaseAgeExclude:
  - "@cerbos/*"
  - react
  - react-dom
  - scheduler

patchedDependencies:
  "@microsoft/api-documenter@7.28.1": patches/@microsoft__api-documenter@7.28.1.patch
