packages:
  - packages/*
  - private/*

ignoredBuiltDependencies:
  - "@bufbuild/buf"
  - esbuild
  - protobufjs

linkWorkspacePackages: true

minimumReleaseAge: 7200 # 5 days
minimumReleaseAgeExclude:
  - "@cerbos/*"
  - react
  - react-dom
  - scheduler
