packages:
  - packages/*
  - private/*

allowBuilds:
  "@bufbuild/buf": false
  esbuild: false
  protobufjs: false

linkWorkspacePackages: true

minimumReleaseAge: 7200 # 5 days
minimumReleaseAgeExclude:
  - "@cerbos/*"
  - react
  - react-dom
  - scheduler

overrides:
  # https://github.com/arethetypeswrong/arethetypeswrong.github.io/issues/258
  "@arethetypeswrong/core@0.18.2>fflate": 0.8.3

saveExact: true
