packages:
  - packages/*
  - private/*

ignoredBuiltDependencies:
  - "@bufbuild/buf"
  - esbuild
  - protobufjs

linkWorkspacePackages: true

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - "@cerbos/*"
  - react
  - react-dom
  - scheduler

patchedDependencies:
  "@microsoft/api-documenter@7.28.0": patches/@microsoft__api-documenter@7.28.0.patch
