packages:
  - packages/*
  - private/*

ignoredBuiltDependencies:
  - "@bufbuild/buf"
  - esbuild
  - protobufjs

linkWorkspacePackages: true

minimumReleaseAge: 4320 # 3 days
minimumReleaseAgeExclude:
  - "@cerbos/*"
  - react
  - react-dom
  - scheduler
