// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// source: protoc-gen-openapiv2/options/annotations.proto

/* eslint-disable */

export const protobufPackage = "grpc.gateway.protoc_gen_openapiv2.options";
