#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

excludes=(--exclude https://www.npmjs.com/)
case "${GITHUB_HEAD_REF:-}" in
  "prepare-release" | "prepare-releases")
    excludes+=(--exclude https://github.com/cerbos/cerbos-sdk-javascript/compare/)
    ;;
esac

check() {
  docker run \
    --interactive \
    --rm \
    --env GITHUB_TOKEN \
    --mount "type=bind,source=${PWD},target=/input" \
    --workdir /input \
    lycheeverse/lychee:0.22.0-alpine \
    "${excludes[@]}" \
    --include-fragments \
    --max-concurrency 8 \
    --remap "^https://cerbos\.github\.io/cerbos-sdk-javascript/ file:///input/docs/" \
    --verbose \
    "$@"
}

git_commit=$(git rev-parse HEAD)

check \
  --root-dir /input \
  .

check \
  --remap "^https://github\.com/[^/]+/cerbos-sdk-javascript/blob/${git_commit}/ file:///input/" \
  docs
