#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

excludes=(
  --exclude https://www.npmjs.com/
  --exclude https://opentelemetry.io/
)

case "${GITHUB_HEAD_REF:-}" in
  "prepare-release" | "prepare-releases")
    excludes+=(--exclude https://github.com/cerbos/cerbos-sdk-javascript/compare/)
    ;;
esac

check() {
  docker compose \
    --file scripts/docker-compose.yaml \
    run \
    --interactive \
    --rm \
    --user "${uid}:${gid}" \
    lychee \
    --config /input/scripts/lychee.toml \
    "${excludes[@]}" \
    --remap "^https://cerbos\.github\.io/cerbos-sdk-javascript/ file:///input/docs/" \
    "$@" \
    2> >(grep -v -E "Skipping fragment check for [^ ]+ within a plaintext file")
}

heading() {
  printf "\n\e[34m%s\e[0m\n" "$1"
}

git_commit=$(git rev-parse HEAD)

uid=$(id -u)
gid=$(id -g)
touch .lycheecache

heading "Checking links in repo"

check \
  --root-dir /input \
  .

heading "Checking links in docs"

check \
  --remap "^https://github\.com/[^/]+/cerbos-sdk-javascript/blob/${git_commit}/ file:///input/" \
  docs
