name: cerbos-sdk-javascript-scripts

services:
  lychee:
    image: lycheeverse/lychee:0.24.2-alpine@sha256:2255c0b916cc8fc4193f59a4549358a6bae0f7d4ea16b5e1dd4c3b2733c35504
    environment:
      - GITHUB_TOKEN
    working_dir: /input
    volumes:
      - type: bind
        source: ../
        target: /input
