name: cerbos-sdk-javascript-scripts

services:
  lychee:
    image: lycheeverse/lychee:0.24.1-alpine@sha256:d74d9df462b4efd68fc8f6f5f7eb5a8f8235b7490137ff1e1a9adb405d140b46
    environment:
      - GITHUB_TOKEN
    working_dir: /input
    volumes:
      - type: bind
        source: ../
        target: /input
