#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

target_dir="$1"

buf generate --template="${target_dir}/buf.gen.yaml"

prettier --log-level=warn --write "${target_dir}/src/protobuf"
