#!/usr/bin/env bash
set -o errexit
set -o nounset
set -o pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

target_dirs=()

while [[ "$1" != "--" ]]; do
  target_dirs+=("$1")
  shift
done

shift

find "${target_dirs[@]}" -type f -execdir "${script_dir}/sed-i" "$@" {} \;
