name: Cache dependencies

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  cache:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Cache dependencies
        uses: ./.github/actions/setup-node

      - name: Lint
        uses: ./.github/actions/lint
        with:
          github-app-client-id: ${{ secrets.CERBOS_BOT_CLIENT_ID }}
          github-app-private-key: ${{ secrets.CERBOS_BOT_PRIVATE_KEY }}
