name: Cache dependencies

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  cache:
    name: Cache dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Cache dependencies
        uses: ./.github/actions/setup-node

      - name: Lint
        uses: ./.github/actions/lint
        with:
          github-app-client-id: ${{ secrets.CERBOS_BOT_CLIENT_ID }}
          github-app-private-key: ${{ secrets.CERBOS_BOT_PRIVATE_KEY }}
