name: Publish package to npm registry

on:
  push:
    tags:
      - "@cerbos/*@*"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  publish:
    name: Publish package to npm registry
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: ./.github/actions/setup-node
        with:
          restore-cache: false
          save-cache: false

      - name: Publish
        run: scripts/publish

      - name: Notify Slack on failure
        if: failure()
        uses: cerbos/actions/notify-slack@e3157d5b6353a7a4e8b0bffe9bc0b57d49b0c1d1 # main
        with:
          webhook-url: ${{ secrets.SLACK_CI_NOTIFICATIONS_WEBHOOK_URL }}
