name: Publish package to npm registry

on:
  push:
    tags:
      - "@cerbos/*@*"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  publish:
    name: Publish package to npm registry
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: ./.github/actions/setup-node
        with:
          cache: false

      - name: Publish
        run: scripts/publish

      - name: Notify Slack on failure
        if: failure()
        uses: cerbos/actions/notify-slack@52f1500fb4d5fffeda0c2f964e4028037b357557 # main
        with:
          webhook-url: ${{ secrets.SLACK_CI_NOTIFICATIONS_WEBHOOK_URL }}
