name: Publish package to npm registry

on:
  push:
    tags:
      - "@cerbos/*@*"

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  publish:
    name: Publish package to npm registry
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: ./.github/actions/setup-node
        with:
          cache: false

      - name: Publish
        run: scripts/publish

      - name: Notify Slack on failure
        if: failure()
        uses: cerbos/actions/notify-slack@5d22d281c9b3bf9a0c8f6cf19090d182cd24d2a2 # main
        with:
          webhook-url: ${{ secrets.SLACK_CI_NOTIFICATIONS_WEBHOOK_URL }}
