name: Audit GitHub Actions security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  zizmor:
    name: Audit GitHub Actions security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: cerbos/actions/lint-actions@aa71e4b2b40b8d8d17b2a9ab3550433ec3fa0729 # main
