name: Audit GitHub Actions security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  zizmor:
    name: Audit GitHub Actions security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: cerbos/actions/lint-actions@e3157d5b6353a7a4e8b0bffe9bc0b57d49b0c1d1 # main
