name: Audit GitHub Actions security

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions: {}

jobs:
  zizmor:
    name: Audit GitHub Actions security
    runs-on: ubuntu-latest
    permissions:
      security-events: write
    steps:
      - name: Check out code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Run zizmor
        uses: cerbos/actions/lint-actions@5d22d281c9b3bf9a0c8f6cf19090d182cd24d2a2 # main
